"""data_fim no concurso

Revision ID: 28280defaf75
Revises: ef6f1c0ccc55
Create Date: 2026-07-04 09:48:03.823360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28280defaf75'
down_revision = 'ef6f1c0ccc55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_fim', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concursos', schema=None) as batch_op:
        batch_op.drop_column('data_fim')

    # ### end Alembic commands ###
