"""schema inicial

Revision ID: 6b957fca088b
Revises: 
Create Date: 2026-07-03 18:23:14.597212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b957fca088b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('concursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('data_prova', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('simulados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('concurso_id', sa.Integer(), nullable=False),
    sa.Column('data_simulado', sa.Date(), nullable=False),
    sa.Column('nota_geral', sa.Float(), nullable=False),
    sa.Column('posicao_estimada', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['concurso_id'], ['concursos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulados_concurso_id'), ['concurso_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulados_user_id'), ['user_id'], unique=False)

    op.create_table('simulado_materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulado_id', sa.Integer(), nullable=False),
    sa.Column('materia', sa.Enum('MATEMATICA', 'FISICA', 'QUIMICA', 'PORTUGUES', 'INGLES', 'REDACAO', name='materia', native_enum=False, length=20), nullable=False),
    sa.Column('acertos', sa.Integer(), nullable=False),
    sa.Column('total_questoes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['simulado_id'], ['simulados.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulado_id', 'materia')
    )
    with op.batch_alter_table('simulado_materias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulado_materias_simulado_id'), ['simulado_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulado_materias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulado_materias_simulado_id'))

    op.drop_table('simulado_materias')
    with op.batch_alter_table('simulados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulados_user_id'))
        batch_op.drop_index(batch_op.f('ix_simulados_concurso_id'))

    op.drop_table('simulados')
    op.drop_table('concursos')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
