"""nota_automatica no simulado

Revision ID: 752e66781be8
Revises: 28280defaf75
Create Date: 2026-07-15 20:09:00.980956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752e66781be8'
down_revision = '28280defaf75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nota_automatica', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulados', schema=None) as batch_op:
        batch_op.drop_column('nota_automatica')

    # ### end Alembic commands ###
