"""materias por concurso

Revision ID: 960aa895df56
Revises: 6b957fca088b
Create Date: 2026-07-03 20:46:31.796569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960aa895df56'
down_revision = '6b957fca088b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('materias_csv', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concursos', schema=None) as batch_op:
        batch_op.drop_column('materias_csv')

    # ### end Alembic commands ###
