"""plano e registro de estudo

Revision ID: ef6f1c0ccc55
Revises: 960aa895df56
Create Date: 2026-07-04 09:18:25.945110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6f1c0ccc55'
down_revision = '960aa895df56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plano_estudo_dias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('materia', sa.Enum('MATEMATICA', 'FISICA', 'QUIMICA', 'PORTUGUES', 'INGLES', 'REDACAO', 'GEOGRAFIA', 'HISTORIA', name='materia', native_enum=False, length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dia_semana', 'materia')
    )
    with op.batch_alter_table('plano_estudo_dias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plano_estudo_dias_user_id'), ['user_id'], unique=False)

    op.create_table('registros_estudo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('materia', sa.Enum('MATEMATICA', 'FISICA', 'QUIMICA', 'PORTUGUES', 'INGLES', 'REDACAO', 'GEOGRAFIA', 'HISTORIA', name='materia', native_enum=False, length=20), nullable=False),
    sa.Column('questoes', sa.Integer(), nullable=False),
    sa.Column('acertos', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'data', 'materia')
    )
    with op.batch_alter_table('registros_estudo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registros_estudo_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_estudo_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros_estudo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registros_estudo_user_id'))
        batch_op.drop_index(batch_op.f('ix_registros_estudo_data'))

    op.drop_table('registros_estudo')
    with op.batch_alter_table('plano_estudo_dias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plano_estudo_dias_user_id'))

    op.drop_table('plano_estudo_dias')
    # ### end Alembic commands ###
